INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador A', 'I7 16GB SSD1T', 5403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador B', 'I7 16GB SSD2T', 6403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador C', 'I7 16GB SSD2T', 1234);

INSERT INTO TBL_CLIENT (NAME, AGE, CITY, GENDER) VALUES ('Vinicíus Porto', 19, 'Itu - SP', 'GAY');
INSERT INTO TBL_CLIENT (NAME, AGE, CITY, GENDER) VALUES ('Gabriela Prado', 19, 'Indaiatuba - SP', 'Feminino');
INSERT INTO TBL_CLIENT (NAME, AGE, CITY, GENDER) VALUES ('Keli Corsato', 40, 'Salto - SP', 'Feminino');
